// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package customer

import (
	"github.com/santosdavid/go-api-v2/infrastructure/repository"
)

// Injectors from wire.go:

func New() (*Handler, error) {
	inMemory := repository.New()
	handler := newHandler(inMemory)
	return handler, nil
}
